version: 'version'

services:
  db: 
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=NAME_DATABASE
      - MYSQL_ROOT_PASSWORD=123456789
    ports:
      - "3307:3306"


# run : docker compose -p test-mysql up -d