version: '3.4'

services:
  mysqldb:
    build: 
      context: ./mysql
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - auth-networks

  server:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    environment:
      - DB_HOST=mysqldb
      - DB_USERNAME=root
      - DB_PASSWORD=123
      - DB_DATABASE=DB_NAME
    ports:
      - 8888:8888
    networks:
      - auth-networks
    command: npm start

networks:
  auth-networks:

volumes:
  db: